### ISSUE TITLE
PDF.js library loading broken

### ISSUE THREAD

**Issue by ericswpark** [anvithks/hugo-embed-pdf-shortcode#18]
**Describe the bug**
The script `src` is incorrect, which means the page breaks as the library will not load.

**To Reproduce**
1. Include the library using the steps in README.
2. Run the local webserver with `hugo serve -D` or deploy

**Expected behavior**
The PDF should display normally.

**Screenshots**
<img width="626" alt="image" src="https://user-images.githubusercontent.com/13326074/123665770-8dfdef00-d873-11eb-824b-ea1d96a78909.png">

The correct URL should be `/js/pdf-js/...`, without the extra slash at the beginning. Manually removing the slash fixes the bug.

Reverting https://github.com/anvithks/hugo-embed-pdf-shortcode/commit/704485be7df2b42eda41c3e24db17d0788992191 fixes the bug as well, but it will break if your site depends on the prepended relative link.

**Comment by ericswpark** [comment]
Seems like the loading is broken even when deployed to GH Pages/Actions.

Reverting https://github.com/anvithks/hugo-embed-pdf-shortcode/commit/704485be7df2b42eda41c3e24db17d0788992191 fixes the problem, but it would break the library for everybody else using relative links.

**Comment by anvithks** [comment]
Thanks for raising this issue. 
Let me take a look.
If you have a fix for this would you be able to raise a PR?
Let me know.

**Comment by Berndinox** [comment]
Same Issue here. Fresh install of hugo as well as the pdf addon.

**Comment by RoneoOrg** [comment]
> Same Issue here. Fresh install of hugo as well as the pdf addon._ Is this Repo maintained?

You may want to change the first line of `embed-pdf.html` to something like

```
<script type="text/javascript" src='{{"/js/pdf-js/build/pdf.js" | relURL}}'></script>
```

I also had to play with the parameter `baseURL` in the `config.toml` file.

You should share a public Git repo to get better advices
