### ISSUE TITLE
It is working FINE locally but NOT on hosted site.

### ISSUE THREAD

**Issue by srigurubyo** [anvithks/hugo-embed-pdf-shortcode#28]
**Describe the bug**
It is working fine while I run hugo on my local server.  But it does not work (and keep rotating) on the hosted hugo site.

**To Reproduce**
Visit -> https://www.sribharathi.tech/about/

**Expected behavior**
It should work in both the modes.

**Screenshots**
<img width="547" alt="image" src="https://user-images.githubusercontent.com/10773464/149794145-fd810184-f387-43b5-8be5-d161e82d6225.png">

**Comment by Hesbadami** [comment]
I second this.

**Comment by anvithks** [comment]
> **Describe the bug** It is working fine while I run hugo on my local server. But it does not work (and keep rotating) on the hosted hugo site.
> 
> **To Reproduce** Visit -> https://www.sribharathi.tech/about/
> 
> **Expected behavior** It should work in both the modes.
> 
> **Screenshots** <img alt="image" width="547" src="https://user-images.githubusercontent.com/10773464/149794145-fd810184-f387-43b5-8be5-d161e82d6225.png">

@srigurubyo Could you please share the link to your repo?

As @Hesbadami mentioned above, the location of the file should be specified with relative URL. 

You can check the code for the demo site [here](https://github.com/opensourcegreasemonkey/hugo-embed-pdf-shortcode-demo) to see how this works.

Let me know if it worked.

**Comment by anvithks** [comment]
I checked the website and seems like you have used another solution.
If you do wish to use the shortcode again please do reach out.
Until then I will be closing this issue. Please feel free to reopen again.
