### ISSUE TITLE
unable to load pdf.worker.js with a baseURL in hugo

### ISSUE THREAD

**Issue by dabrain34** [anvithks/hugo-embed-pdf-shortcode#3]
**Describe the bug**
in a hugo page with a different root page than ./ such as: localhost:1313/hugopage/, the js-pdf can not load, getting:

 Setting up fake worker failed: "Cannot load script at: https://localhost:1313/js/pdf-js/build/pdf.worker.js".

**To Reproduce**
 1. run: `hugo server --bind "" --baseURL "localhost/multimedia/"`
 2. Try to load a markdown with {{< embed-pdf url="essai.pdf">}}

**Expected behavior**
The pdf should load correctly

**Desktop (please complete the following information):**
 - Linux
 - Firefox/Chrome

**Additional context**
Very important to change the BaseURL

**Comment by anvithks** [comment]
Hey thanks for raising this issue @dabrain34 
Let me check this out and get back to you.

**Comment by anvithks** [comment]
Hey @dabrain34 I tried to reproduce this and was able to render the pdf.
is there a sample repository where you have your site?
Would it be possible to setup a sample repository with your code which I can clone and test.
