### ISSUE TITLE
',' expected. 

### ISSUE THREAD

**Issue by Dicky1** [anvithks/hugo-embed-pdf-shortcode#6]
https://github.com/anvithks/hugo-embed-pdf-shortcode/blob/99a770df5db08372024eb9470055896e400379d0/layouts/shortcodes/embed-pdf.html#L30

**Comment by anvithks** [comment]
@Dicky1 Thank you for the issue @Dicky1 .
Could you please elaborate a little bit on the issue?

**Comment by Dicky1** [comment]
![Uploading Screenshot_20210305_103851.png…]()

**Comment by Dicky1** [comment]
![Screenshot_20210305_103851](https://user-images.githubusercontent.com/26633820/110065479-c730c180-7da1-11eb-9ba8-8b57db5663eb.png)

**Comment by Dicky1** [comment]
![Screenshot_20210305_105936](https://user-images.githubusercontent.com/26633820/110065598-1971e280-7da2-11eb-8b3b-64be1402cde4.png)
and i tried setting the path but the file is not reading
`{{< embed-pdf url="/Documents/blog-hugo/pdf/file/LAPORAN HASIL MONITORING KEAMANAN SIBER TAHUN 2020.pdf" >}}`

am I correct the path?

**Comment by anvithks** [comment]
> ![Screenshot_20210305_103851](https://user-images.githubusercontent.com/26633820/110065479-c730c180-7da1-11eb-9ba8-8b57db5663eb.png)

@Dicky1 This error is shown as the IDE is expecting HTML syntax but it is  Go HTML Template syntax.
I checked and changing it to the following does not throw the error anymore:
`var url = '{{ .Get "url" }}';`

**Comment by Dicky1** [comment]
okay clear. i found the error returned i tried to set the path but the file is not reading

**Comment by Dicky1** [comment]
![Screenshot_20210305_140227](https://user-images.githubusercontent.com/26633820/110079319-8cd41e00-7dbb-11eb-92ea-4034545c31af.png)

**Comment by anvithks** [comment]
@Dicky1 were you able to fix the issue of the file path?
I am sorry but your message above wasn't clear.

Let me know if you want to raise a PR for the change for the error fix above.
