### ISSUE TITLE
how to set a pdf file so that it can display?

### ISSUE THREAD

**Issue by Dicky1** [anvithks/hugo-embed-pdf-shortcode#7]
![Screenshot_20210305_224426](https://user-images.githubusercontent.com/26633820/110138467-9afa5c80-7e04-11eb-967f-321fdeec542a.png)

I tried the inspect element on the Hugo blog page, an error appeared like the picture

`{{< embed-pdf url="./path/to/pdf/file/LAPORAN HASIL MONITORING KEAMANAN SIBER TAHUN 2020.pdf" >}}`

is it correct to set the url?

**Comment by Dicky1** [comment]
![Screenshot_20210306_000425](https://user-images.githubusercontent.com/26633820/110148619-9c7d5200-7e0f-11eb-81ee-8e1014a962c0.png)

**Comment by anvithks** [comment]
@Dicky1 have you followed the steps to setup the short code correctly? 
Is this on your local machine or a VM? 
From the error it seems that the PdfJsLib is blocked.

**Comment by anvithks** [comment]
After you have setup the shortcode correctly you have to place the pdf file in the content folder where the document exists and specify the relative path to that folder.
For ex: 
if your hugo site is in a folder called blog-hugo this would be an example code.
This would be a sample document `/blog-hugo/content/demo-page/index.md`
Your pdf file should be in the same folder as follows:
`/blog-hugo/content/demo-page/LAPORAN HASIL MONITORING KEAMANAN SIBER TAHUN 2020.pdf`

and in the index.md file you should use the shortcode as follows:

`{{< embed-pdf url="./LAPORAN HASIL MONITORING KEAMANAN SIBER TAHUN 2020.pdf" >}}`

**Comment by anvithks** [comment]
Another suggestion: avoid having spaces in the file name of the PDF file. You can use `-` or `_` like
`LAPORAN_HASIL_MONITORING_KEAMANAN_SIBER_TAHUN_2020.pdf`

**Comment by Dicky1** [comment]
![Screenshot_20210306_022038](https://user-images.githubusercontent.com/26633820/110163435-9775ce00-7e22-11eb-9d4b-2cd5d1efca8e.png)

still the same pdf file does not appear

**Comment by anvithks** [comment]
Have you copied the pdf-js files as per step 3 in the setup [here](https://github.com/anvithks/hugo-embed-pdf-shortcode/blob/master/README.md#setup)?

**Comment by Dicky1** [comment]
Already, is it possible that my pdf file is too big?

**Comment by anvithks** [comment]
> Already, is it possible that my pdf file is too big?

What is the size of the file? 
I do not think the error that you are seeing is because of that. 
is it possible to push your code and share the repository with me? 
I can test it locally and check if there is something that needs to be fixed.

**Comment by Dicky1** [comment]
[Github](https://github.com/Dicky1/hugo-blog)

that's my repository for this problem

**Comment by anvithks** [comment]
@Dicky1 Got it. I pulled your repository. 
One thing that needs to be fixed in your repository is in the JS folder here `https://github.com/Dicky1/hugo-blog/tree/main/static/js`

The `build`, `web` folders and `LICENSE` should be inside a folder called `pdf-js`.
You can take a look at the demo [here](https://github.com/opensourcegreasemonkey/hugo-embed-pdf-shortcode-demo/tree/master/static)

Your pdf file is OK. 
I checked it on my local dev env. The filename without spaces is not a problem.

![image](https://user-images.githubusercontent.com/19162717/110276670-a5ca1280-7ff9-11eb-97fa-f5703b1ce5c7.png)

**Comment by Dicky1** [comment]
I've moved the file in the pdf-js folder I think it's still the same

![Screenshot_20210308_122459](https://user-images.githubusercontent.com/26633820/110278217-6a374480-8009-11eb-9a39-4a54e0b327f0.png)

may check my latest repository

[blog-hugo](https://github.com/Dicky1/hugo-blog/tree/main/static)

**Comment by anvithks** [comment]
I figured it out.
The PDF file is inside the `/post` folder.
![image](https://user-images.githubusercontent.com/19162717/110278768-e3c93580-7ffd-11eb-9db8-58c39df286d5.png)

This is the folder structure.
![image](https://user-images.githubusercontent.com/19162717/110278941-3c98ce00-7ffe-11eb-8cdd-d9ac4bf977f1.png)

Move the PDF file under `/post` folder.
`{{< embed-pdf url="./post/LAPORAN HASIL MONITORING KEAMANAN SIBER TAHUN 2020.pdf" >}}`

if you want to maintain all resources under one folder then you can create a `file/` folder under the post folder.

**Comment by Dicky1** [comment]
oke solved thanks

**Comment by anvithks** [comment]
Closing since the issue was resolved.
